"""Add notificationItem model

Revision ID: 0e44707fa4f6
Revises: 5eb47be2414c
Create Date: 2022-04-29 09:02:46.426764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e44707fa4f6'
down_revision = '5eb47be2414c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_item_id'), 'notification_item', ['id'], unique=False)
    op.create_index(op.f('ix_notification_item_notification_id'), 'notification_item', ['notification_id'], unique=False)
    op.alter_column('notification', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notification', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('notification', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_notification_item_notification_id'), table_name='notification_item')
    op.drop_index(op.f('ix_notification_item_id'), table_name='notification_item')
    op.drop_table('notification_item')
    # ### end Alembic commands ###
