"""Add type to actions

Revision ID: 256ba522e545
Revises: d5f29bd1a40b
Create Date: 2022-05-20 08:57:32.214004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256ba522e545'
down_revision = 'd5f29bd1a40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'type')
    # ### end Alembic commands ###
