"""Add tracking models

Revision ID: 2cd4e207177f
Revises: 0e44707fa4f6
Create Date: 2022-04-30 18:19:51.474153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cd4e207177f'
down_revision = '0e44707fa4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_organisation_id'), 'notifications', ['organisation_id'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_index(op.f('ix_platforms_organisation_id'), 'platforms', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_platforms_slug'), 'platforms', ['slug'], unique=False)
    op.create_index(op.f('ix_platforms_type'), 'platforms', ['type'], unique=False)
    op.create_table('notification_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_items_id'), 'notification_items', ['id'], unique=False)
    op.create_index(op.f('ix_notification_items_notification_id'), 'notification_items', ['notification_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_id'), 'tracking_events', ['id'], unique=False)
    op.create_table('tracking_event_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tracking_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_event_id'], ['tracking_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_event_sessions_id'), 'tracking_event_sessions', ['id'], unique=False)
    op.create_table('tracking_event_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('tracking_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_event_id'], ['tracking_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_event_triggers_id'), 'tracking_event_triggers', ['id'], unique=False)
    op.drop_index('ix_notification_item_id', table_name='notification_item')
    op.drop_index('ix_notification_item_notification_id', table_name='notification_item')
    op.drop_table('notification_item')
    op.drop_index('ix_platform_id', table_name='platform')
    op.drop_index('ix_platform_organisation_id', table_name='platform')
    op.drop_index('ix_platform_slug', table_name='platform')
    op.drop_index('ix_platform_type', table_name='platform')
    op.drop_table('platform')
    op.drop_index('ix_notification_id', table_name='notification')
    op.drop_index('ix_notification_organisation_id', table_name='notification')
    op.drop_table('notification')
    op.add_column('actions', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('actions', sa.Column('tracking_event_trigger_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_actions_tracking_event_trigger_id'), 'actions', ['tracking_event_trigger_id'], unique=False)
    op.create_foreign_key(None, 'actions', 'tracking_event_triggers', ['tracking_event_trigger_id'], ['id'], ondelete='SET NULL')
    op.drop_column('actions', 'model_name')
    op.drop_column('actions', 'model_method_kwargs')
    op.drop_column('actions', 'model_id')
    op.drop_column('actions', 'model_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('model_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('model_method_kwargs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_index(op.f('ix_actions_tracking_event_trigger_id'), table_name='actions')
    op.drop_column('actions', 'tracking_event_trigger_id')
    op.drop_column('actions', 'data')
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('notification_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name='notification_organisation_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='notification_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_notification_organisation_id', 'notification', ['organisation_id'], unique=False)
    op.create_index('ix_notification_id', 'notification', ['id'], unique=False)
    op.create_table('platform',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subdomain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name='platform_organisation_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='platform_pkey')
    )
    op.create_index('ix_platform_type', 'platform', ['type'], unique=False)
    op.create_index('ix_platform_slug', 'platform', ['slug'], unique=False)
    op.create_index('ix_platform_organisation_id', 'platform', ['organisation_id'], unique=False)
    op.create_index('ix_platform_id', 'platform', ['id'], unique=False)
    op.create_table('notification_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], name='notification_item_notification_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='notification_item_pkey')
    )
    op.create_index('ix_notification_item_notification_id', 'notification_item', ['notification_id'], unique=False)
    op.create_index('ix_notification_item_id', 'notification_item', ['id'], unique=False)
    op.drop_index(op.f('ix_tracking_event_triggers_id'), table_name='tracking_event_triggers')
    op.drop_table('tracking_event_triggers')
    op.drop_index(op.f('ix_tracking_event_sessions_id'), table_name='tracking_event_sessions')
    op.drop_table('tracking_event_sessions')
    op.drop_index(op.f('ix_tracking_events_id'), table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_notification_items_notification_id'), table_name='notification_items')
    op.drop_index(op.f('ix_notification_items_id'), table_name='notification_items')
    op.drop_table('notification_items')
    op.drop_index(op.f('ix_platforms_type'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_slug'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_organisation_id'), table_name='platforms')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_notifications_organisation_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
