"""add_actions

Revision ID: 2e4475076af0
Revises: 50cfa74c1775
Create Date: 2022-03-23 23:08:56.684850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4475076af0'
down_revision = '50cfa74c1775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execute_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_triggers_id'), 'schedule_triggers', ['id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_method', sa.String(), nullable=True),
    sa.Column('model_method_kwargs', sa.JSON(), nullable=True),
    sa.Column('schedule_trigger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_trigger_id'], ['schedule_triggers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_index(op.f('ix_actions_schedule_trigger_id'), 'actions', ['schedule_trigger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_schedule_trigger_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_schedule_triggers_id'), table_name='schedule_triggers')
    op.drop_table('schedule_triggers')
    # ### end Alembic commands ###
