"""Add fields to EventSession

Revision ID: 34f3c0a9d1db
Revises: 256ba522e545
Create Date: 2022-05-20 12:15:30.766205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f3c0a9d1db'
down_revision = '256ba522e545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('event_sessions', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('event_sessions', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('event_sessions', sa.Column('tracking_event_id', sa.Integer(), nullable=True))
    op.drop_constraint('event_sessions_event_id_fkey', 'event_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'event_sessions', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_sessions', 'events', ['tracking_event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_sessions', type_='foreignkey')
    op.drop_constraint(None, 'event_sessions', type_='foreignkey')
    op.create_foreign_key('event_sessions_event_id_fkey', 'event_sessions', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    op.drop_column('event_sessions', 'tracking_event_id')
    op.drop_column('event_sessions', 'date')
    op.drop_column('event_sessions', 'end_time')
    op.drop_column('event_sessions', 'start_time')
    # ### end Alembic commands ###
