"""add_events

Revision ID: 50cfa74c1775
Revises: b5f6b8ab445c
Create Date: 2022-03-23 22:56:23.532764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cfa74c1775'
down_revision = 'b5f6b8ab445c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=True),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('event_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sessions_id'), 'event_sessions', ['id'], unique=False)
    op.drop_constraint('organisations_users_user_id_fkey', 'organisations_users', type_='foreignkey')
    op.drop_constraint('organisations_users_organisation_id_fkey', 'organisations_users', type_='foreignkey')
    op.create_foreign_key(None, 'organisations_users', 'organisations', ['organisation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'organisations_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisations_users', type_='foreignkey')
    op.drop_constraint(None, 'organisations_users', type_='foreignkey')
    op.create_foreign_key('organisations_users_organisation_id_fkey', 'organisations_users', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key('organisations_users_user_id_fkey', 'organisations_users', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_event_sessions_id'), table_name='event_sessions')
    op.drop_table('event_sessions')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
