"""Add tracking models

Revision ID: 56fffb8948a7
Revises: 2cd4e207177f
Create Date: 2022-04-30 18:21:42.669103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fffb8948a7'
down_revision = '2cd4e207177f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
