"""Add notification model

Revision ID: 5eb47be2414c
Revises: 6533d09269a1
Create Date: 2022-04-29 08:34:49.635057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb47be2414c'
down_revision = '6533d09269a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_organisation_id'), 'notification', ['organisation_id'], unique=False)
    op.alter_column('platform', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_platform_type'), 'platform', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_type'), table_name='platform')
    op.alter_column('platform', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_notification_organisation_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
