"""Add name to event models

Revision ID: 75497aaa5368
Revises: a1040b2a322f
Create Date: 2022-05-03 20:42:10.525912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75497aaa5368'
down_revision = 'a1040b2a322f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=False))
    op.add_column('tracking_events', sa.Column('name', sa.String(), nullable=False))
    op.add_column('tracking_events', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_events', 'type')
    op.drop_column('tracking_events', 'name')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
