"""Add interval to tracking event model

Revision ID: d5f29bd1a40b
Revises: d2bbfacba80a
Create Date: 2022-05-03 20:55:17.469633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f29bd1a40b'
down_revision = 'd2bbfacba80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_events', sa.Column('interval', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_events', 'interval')
    # ### end Alembic commands ###
