"""Add event_data field to event

Revision ID: e9245e418b8d
Revises: 34f3c0a9d1db
Create Date: 2022-05-20 20:07:42.582355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9245e418b8d'
down_revision = '34f3c0a9d1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('event_data', sa.JSON(), nullable=True))
    op.drop_constraint('event_sessions_tracking_event_id_fkey', 'event_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'event_sessions', 'tracking_events', ['tracking_event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_sessions', type_='foreignkey')
    op.create_foreign_key('event_sessions_tracking_event_id_fkey', 'event_sessions', 'events', ['tracking_event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('event_sessions', 'event_data')
    # ### end Alembic commands ###
